name: test-java

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo y chequear repo
        uses: actions/checkout@v4

      - name: configurar java con temurin jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Dar permisos de ejecución a mvnw
        run: chmod +x ./mvnw

      - name: test code java spring boot
        run: ./mvnw clean test
