name: test-java
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Obtener codigo y chequear repo
      uses: actions/checkout@v2

    - name: configurar java con temuin jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: test code java spring boot
      run: |
        ./mvnw clean test
